### ISSUE TITLE
Data generator 

### ISSUE THREAD

**Issue by gedw99** [gsmonni/ldapsvc#35]
Would like to extend to enable gen of the data to help with testing 

First step is the vets 

then the data 

if you have any ideas on this should and then I can do it.

I also have builds and tests running cross platform that I will PR.

**Comment by gsmonni** [comment]
@gedw99 as of now the data-generation and parsing is done only via mock-data. I implemented a generic query module on the mock data. 
tbh I developed but i havent had the chance to test the LDAP query module. if ur planning to use the service to query actual ldap backends  probably one of the first things to work on would be testing ldap backend (eg using a openldap docker container)...

**Comment by gedw99** [comment]
thanks @gsmonni 

Ok I see your point... I can work on that and PR it if you want ?

My intent is to build up a nice LDAP backend for auth that can be as  for other golang apps.

The swagger GUi is nice for seeing the data.. Was thinking about a Read / write gui based on HTMX and golang too... 


Let me know if some of this gels with you :)

**Comment by gsmonni** [comment]
@gedw99  sure thanks feel free to submit the PR with ldap backend tests, ill be happy to review it. 
re UI, my use case doesnt need a full fledged UI, but it would be a great add on, should u wish to work on it. 
thx for ur help, and happy new year!
s

**Comment by gedw99** [comment]
Cheers :)

**Comment by gedw99** [comment]
https://github.com/glauth/glauth Looks like a decent base to me ? 

We need a ldap server to test against right ?

**Comment by gsmonni** [comment]
@gedw99 sure that would work (tbh the only requirement is to use a stadard openldap backend)
